version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5173:5173"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: TodoDB
      DB_PORT: 3306
    networks:
      - app-network

  db:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TodoDB
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5050:5050"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:5000/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge